source 'http://rubygems.org'

gem 'eventmachine', '1.0.0.beta.3'
gem 'em-synchrony'
gem 'nokogiri'
gem 'bson_ext'
gem 'mongoid'
gem 'will_paginate'
gem 'sinatra'
gem 'sinatra-synchrony'
gem 'haml'
gem 'thin'
